language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly 
sudo: required
dist: trusty
os:
  - linux
install:
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get update
  - sudo apt-get install libsodium-dev -y
addons:
  apt:
    packages:
      - libcryptsetup-dev
      - libykpers-1-dev
        #- libsodium-dev
# libsodium is not available on older releases
notifications:
  email:
    on_success: never